# Site settings
title: gamestism
description: CS:GO Player
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://gamestism.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: gamestism
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: CS:GO Player
email: andrew@baxtrweb.com
twitter_username: gamestism
steam_username: gamestism
instagram_username: gamestism

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
